# Generated by Django 3.1.5 on 2021-03-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210305_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(default='main/covers/default.png', max_length=100),
        ),
    ]
