# Generated by Django 3.1.5 on 2021-04-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210313_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.TextField(default='{}'),
        ),
    ]
