# Generated by Django 3.1.5 on 2021-05-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210509_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='show_on_main',
            field=models.BooleanField(default=False),
        ),
    ]
