# Generated by Django 3.1.5 on 2021-06-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_top_show_on_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
